# Generated by Django 3.0.4 on 2020-04-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RaiseTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=50)),
                ('account_name', models.CharField(max_length=30)),
                ('approver_name', models.CharField(max_length=30)),
                ('request_type', models.CharField(max_length=30)),
                ('requestor_priority', models.CharField(choices=[('P1', 'Priority_1'), ('P2', 'Priority_2'), ('P3', 'Priority_3'), ('P4', 'Priority_4')], default='P1', max_length=2)),
                ('task_status', models.CharField(choices=[('new', 'new'), ('open', 'open'), ('development', 'development'), ('testing', 'testing'), ('closed', 'closed')], default='new', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('assignee', models.CharField(default='null', max_length=50)),
                ('request_description', models.TextField()),
            ],
        ),
    ]
